version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: BoltPostgres
    volumes:
      - ~/BoltPostgres:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=bolt
      - POSTGRES_USER=bolt
      - POSTGRES_PASSWORD=zaq12wsx

  gethpoa:
    image: geth-poa
    container_name: BoltGethPoA
    volumes:
      - ~/BoltGethPoA:/home/ubuntu/shares
    expose:
      - 8545
      - 8546
    ports:
      - 8545:8545
      - 8546:8546
